// calendar

Table bronze_calendar {
	date_day varchar
	year varchar
	quarter varchar
	month varchar
	day_of_month varchar
	day_of_week varchar
	day_name varchar
	week_of_year varchar
	is_weekend varchar
	is_polish_public_holiday varchar
	holiday_name varchar
	load_date varchar
	loaded_at varchar
	_source_system varchar
	_source_entity varchar
	_source_file_name varchar
	_source_load_date varchar
	_source_file_path varchar
	_ingestion_run_id varchar
	_ingested_at varchar
	_raw_record_hash varchar
}

Table silver_calendar {
  date_day date
  year integer
  quarter integer
  month integer
  day_of_month integer
  day_of_week integer
  day_name varchar
  week_of_year integer
  is_weekend boolean
  is_polish_public_holiday boolean
  holiday_name varchar
}

Table dim_calendar {
  date_key int [pk, not null]

  date_day date [not null, unique]

  year int [not null]
  quarter int [not null]
  month int [not null]
  month_name varchar [not null]
  day_of_month int [not null]
  day_of_week int [not null]
  day_name varchar [not null]
  week_of_year int [not null]

  is_weekend boolean [not null]

  is_polish_public_holiday boolean [not null]
  holiday_name varchar
  
  _gold_processed_at timestamp [not null]
}

// customers

Table bronze_customers {
    customer_id varchar
    email varchar
    first_name varchar
    last_name varchar
    country_code varchar
    city varchar
    created_at varchar
    updated_at varchar
    customer_status varchar
    marketing_consent varchar
    load_date varchar
    loaded_at varchar
    source_event_at varchar
    _source_system varchar
    _source_entity varchar
    _source_file_name varchar
    _source_load_date varchar
    _source_file_path varchar
    _ingestion_run_id varchar
    _ingested_at varchar
    _raw_record_hash varchar
}

Table silver_customers {
    customer_id varchar
    email varchar
    first_name varchar
    last_name varchar
    country_code varchar
    city varchar
    created_at timestamp
    updated_at timestamp
    customer_status varchar
    marketing_consent boolean
    load_date date
    loaded_at timestamp
    source_event_at timestamp
    _silver_processed_at timestamp
}

Table dim_customers {
  customer_key bigint [pk]
  customer_id varchar [not null, unique]

  email varchar
  email_domain varchar
  
  first_name varchar
  last_name varchar
  full_name varchar

  country_code varchar
  city varchar

  customer_status varchar
  is_active_customer boolean
  marketing_consent boolean

  registered_at timestamp
  registration_date_key int [ref: > dim_calendar.date_key]

  _gold_processed_at timestamp
}

