Table silver_calendar {
  date_day date
  year integer
  quarter integer
  month integer
  day_of_month integer
  day_of_week integer
  day_name varchar
  week_of_year integer
  is_weekend boolean
  is_polish_public_holiday boolean
  holiday_name varchar
}

Table silver_exchange_rate {
  exchange_rate_key bigint [pk]

  rate_date_key varchar
  rate_date date

  currency varchar
  rate_to_pln decimal(5, 4)

  source varchar
  loaded_at varchar

  _silver_processed_at timestamp
}