# Azure constants
STORAGE_ACCOUNT_NAME = "storderflowdevfrc1"
LAKEHOUSE_CONTAINER = "lakehouse"

SECRET_SCOPE = "orderflow"
STORAGE_ACCOUNT_KEY_SECRET_NAME = "storderflowdevfrc1-key"

ADLS_SOURCE_SYSTEM = "adls_raw"

ADLS_BASE_PATH = f"abfss://{LAKEHOUSE_CONTAINER}" f"@{STORAGE_ACCOUNT_NAME}.dfs.core.windows.net"

# Unity Catalog objects created by the Databricks setup notebooks.
ORDERFLOW_CATALOG = "orderflow_dev"
LANDING_VOLUME_PATH = f"/Volumes/{ORDERFLOW_CATALOG}/bronze/landing"

CALENDAR_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/calendar"
CUSTOMERS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/customers"
MARKETING_CAMPAIGNS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/marketing_campaigns"
ORDER_ITEMS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/order_items"
ORDERS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/orders"
PAYMENTS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/payments"
PRODUCTS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/products"
REFUNDS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/refunds"
SHIPMENTS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/shipments"
WEB_EVENTS_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/web_events"
EXCHANGE_RATES_BRONZE_INPUT_PATH = f"{LANDING_VOLUME_PATH}/exchange_rates"

CALENDAR_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.calendar"
CUSTOMERS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.customers"
MARKETING_CAMPAIGNS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.marketing_campaigns"
ORDER_ITEMS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.order_items"
ORDERS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.orders"
PAYMENTS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.payments"
PRODUCTS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.products"
REFUNDS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.refunds"
SHIPMENTS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.shipments"
WEB_EVENTS_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.web_events"
EXCHANGE_RATES_BRONZE_TABLE = f"{ORDERFLOW_CATALOG}.bronze.exchange_rates"

CALENDAR_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.calendar"
CUSTOMERS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.customers"
MARKETING_CAMPAIGNS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.marketing_campaigns"
ORDER_ITEMS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.order_items"
ORDERS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.orders"
PAYMENTS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.payments"
PRODUCTS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.products"
REFUNDS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.refunds"
SHIPMENTS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.shipments"
WEB_EVENTS_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.web_events"
EXCHANGE_RATES_SILVER_TABLE = f"{ORDERFLOW_CATALOG}.silver.exchange_rates"

CALENDAR_GOLD_TABLE = f"{ORDERFLOW_CATALOG}.gold.dim_calendar"
CUSTOMERS_GOLD_TABLE = f"{ORDERFLOW_CATALOG}.gold.dim_customers"
